theme: jekyll-theme-slate
remote_theme : mmistakes/minimal-mistakes
url     : "https://sixsaku.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl : "" # the subpath of your site, e.g. "/blog"
